# -*- coding: utf-8 -*-
"""board_conversion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I6PL8Sr2HX6xeaBPf4MLcu5Z_D0NbF4R
"""

chess_dict = {
    'p' : [1,0,0,0,0,0,0,0,0,0,0,0],
    'P' : [0,0,0,0,0,0,1,0,0,0,0,0],
    'n' : [0,1,0,0,0,0,0,0,0,0,0,0],
    'N' : [0,0,0,0,0,0,0,1,0,0,0,0],
    'b' : [0,0,1,0,0,0,0,0,0,0,0,0],
    'B' : [0,0,0,0,0,0,0,0,1,0,0,0],
    'r' : [0,0,0,1,0,0,0,0,0,0,0,0],
    'R' : [0,0,0,0,0,0,0,0,0,1,0,0],
    'q' : [0,0,0,0,1,0,0,0,0,0,0,0],
    'Q' : [0,0,0,0,0,0,0,0,0,0,1,0],
    'k' : [0,0,0,0,0,1,0,0,0,0,0,0],
    'K' : [0,0,0,0,0,0,0,0,0,0,0,1],
    '.' : [0,0,0,0,0,0,0,0,0,0,0,0],
}
import numpy as np
def translate(board):
    print(board)
    pgn = str(board)
    foo = []
    #foo_String = str(foo)  
    #pieces = pgn.split(" ", 1)
    pieces = pgn.split("/")
    stringPieces=str(pieces)
    print('pieces' + stringPieces)
    rows = stringPieces.split("/")
    stringRows=str(rows)
    print('rows'+stringRows)
    #thing='r'
    thing = np.array[0,0,0,1,0,0,0,0,0,0,0,0]
    for row in rows:
        foo2 = []  
        for thing in rows:
           if thing.isdigit():
                for i in range(0, (thing)):
                    foo2.append(chess_dict['.'])
                    print('this is thing_if' + (thing))
           else:
                print('this is thing_else' + (thing))
                foo2.append(chess_dict[thing])
    foo.append(foo2)
    thing_string = str(thing)
    foo2String=str(foo2)
    print('this is thing_end' + thing_string)
    print('this is foo2' + foo2String)
    return foo

from google.colab import drive
drive.mount('/content/drive')